### ISSUE TITLE
The absence of a vendor directory in the community edition

### ISSUE THREAD

**Issue by AlexandrRSU** [ONLYOFFICE/Kubernetes-Docs#327] opened 2024-11-13 12:17 UTC
Hey, guys! I'm trying to use your community version of proxy, docservice and converter. It seems like "vendor" directory (/var/www/onlyoffice/documentserver/web-apps) not present in community edition images (without de and ee suffix). Is it ok?

**Comment by AlexandrRSU** [comment] 2024-11-14 11:50
@agolybev @VyacheslavSemin Need your help

**Comment by alexonlyoffice** [comment] 2024-11-14 13:02
hello @AlexandrRSU, this folder is present in proxy and converter containers, but it is not added to docservice container - this is applicable for all packages ee, de and open source as well. Do you encounter any issues when using the Document Server? If yes, please describe them in more details.

**Comment by AlexandrRSU** [comment] 2024-11-14 14:42
@alexonlyoffice Sorry, I wasn't clear. I got this error in proxy 
open () "/var/www/onlyoffice/documentserver/web-apps/vendor/socketio/socket.io.min.js.map" failed (2: No such file or directory). Can you help me with it?

**Comment by igwyd** [comment] 2024-11-14 16:01
Hello @AlexandrRSU,
Duplicate of #https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/644

**Comment by AlexandrRSU** [comment] 2024-11-14 16:57
Ty for the help, I'm closing the issue

**Closed** 2024-11-14 16:57 UTC
